name: Deploy to AWS with PipeCD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger PipeCD deployment
        run: |
          curl -X POST https://your-pipedc-url/api/v1/pipelines/trigger \
          -d '{"application": "hello-world-app", "env": "production"}'
