name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.22.2

      - name: Terraform fmt
        run: terraform fmt -check

      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.24.4'

      - name: "run tests"
        run: |
          go test -run Validation -v ./... -timeout=30s
