name: Run tests

on:
  pull_request:
    branches:
      - main
  merge_group:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Terraform fmt
        run: terraform fmt -check

      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.24.4'

      - name: "run validation tests"
        run: |
          go test -run Validation -v ./... -timeout=10m

      - name: "run integration tests"
        if: ${{ github.event_name == 'merge_group' }}
        run: |
          go test -run VPC -v ./... -timeout=60m
